inherit_from:
  - .rubocop_todo.yml
  - ./rubocop/rubocop_rails.yml
  - ./rubocop/rubocop_rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec
  - ./rubocop/rubocop

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - .circleci/*
    - db/migrate/*
    - db/schema.rb
    - bin/bundle
    - rubocop/**/*.rb

Layout/LineLength:
  Max: 100
  Exclude:
    - config/**/*

Lint/MissingSuper:
  Exclude:
    - app/services/bill_processor.rb

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake

Rails/I18nLocaleTexts:
  Exclude:
    - app/models/order.rb

Rails/InverseOf:
  Exclude:
    - app/models/food.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/controllers/api/v1/orders_controller.rb

Rails/TransactionExitStatement:
  Exclude:
    - app/controllers/api/v1/orders_controller.rb

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/discount.rb
    - app/models/line_item.rb

RSpec/ExampleLength:
  Exclude:
    - spec/requests/**/*.rb

RSpec/LetSetup:
  Exclude:
    - spec/requests/**/*.rb
    - spec/services/*.rb

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/requests/**/*.rb
    - spec/services/*.rb

RSpec/RepeatedDescription:
  Exclude:
    - spec/requests/**/*.rb

RSpec/RepeatedExample:
  Exclude:
    - spec/requests/**/*.rb

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - config/initializers/strong_migrations.rb
